name: "Testning CI"

on:
  push:
    branches:
      ["master"]

  pull_request:
    branches:
     ["master"]

  jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkoutv5

        - name: Setup JAVA
          with:
            distribution: 'jetbrains'
            java-version: '21'

        - name: Run tests
          run: ./mvnw test